#!/usr/bin/env bash

set -e
echo "Installing..."

progs=$(ls -d */)

for p in ${progs[@]}; do
  echo " * Stowing $p..."
  stow -t ~ $p
done

echo ""
echo "Done stowing! ✅"

echo ""
echo "Installing latest Ruby..."
curl -sSL https://get.rvm.io | bash -s stable --ruby

echo ""
echo "Installing brew..."
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
echo "Done installing brew! ✅"

echo ""
echo "Installing brews and casks...""
brew bundle -v 

echo ""
echo "Done! ✅"

exit 0
