#!/usr/bin/env bash

set -e

# Install Brew.

echo ""
echo "Installing brew..."
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
echo "Done installing brew! ✅"

# Install Ruby via RVM.

echo ""
echo "Installing latest Ruby..."
curl -sSL https://get.rvm.io | bash -s stable --ruby

# Install Stow and stow configs.

brew install stow

echo "Stowing configs..."

progs=$(ls -d */)

for p in ${progs[@]}; do
  echo " * Stowing $p..."
  stow -t ~ $p
done

echo ""
echo "Done stowing! ✅"

# Install Brewfile dependencies.

echo ""
echo "Installing remaining brews and casks...""
brew bundle -v

echo ""
echo "Done! ✅"

exit 0
